version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile : Dockerfile 
    command: 'python app.py'
    ports:
      - 5000:5000
    volumes:
      - .:/app  
    depends_on:
      - db


  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db



  db:
    image: mysql:5.7.22
    command: --explicit_defaults_for_timestamp
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306